#!/usr/bin/Rscript

## Original Source: github.com/yihui/knitr-book/knit.sh
## Author         : Yihui Xie
## Modified       : Ramnath Vaidyanathan

## LOAD KNITR LIBRARY -----------------------------------------------------
library(knitr)
library(ascii)
options(asciiType = 'rest')

## INPUT PATTERN FOR CODE CHUNKS --------------------------------
## `ro [global options] or`
## ``` {r code begin} [block code] ````
## `ri [inline code] ir`

pat_md()       

## SET RST AS OUTPUT FORMAT -------------------------------------
render_rst()

## SET KNITR OPTIONS --------------------------------------------
opts_knit$set(
  out.format = 'gfm',
  tidy       = FALSE,
  base.url   = '_knit/'
)
## SET CHUNK OPTIONS --------------------------------------------
opts_chunk$set(
	dev        = 'png',
	fig.path   = "_figures/",
	cache.path = ".cache/",
	fig.width  = 6,
	fig.height = 6,
	fig.align  = "center"
)

hook_out = knit_hooks$get('output')

knit_hooks$set(output = function(x, options){
   if (options$results == 'html'){
      content = knitr:::make_directive('raw', 'html', '', paste(x, collapse = '\n'))
      paste(c('\n\n.. only:: html\n', knitr:::indent_block(content), ''), collapse = '\n')
   } else {
     hook_out(x, options)
   }
})

make_image <- function(r1, path){
  r1$save(path, cdn = TRUE)
  img <- gsub(".html$", "", path)
  invisible(take_screenshot(path, img))
  cat(knitr:::make_directive('image', sprintf('_knit/%s.png', img), ""))
}
make_iframe <- function(r1){
  content = paste(capture.output(r1$show('iframesrc', cdn = TRUE)), collapse = '\n')
  cat(knitr:::make_directive('raw', 'html', '', content))
}


## KNIT DOCUMENT ------------------------------------------------
args = commandArgs(trailingOnly = TRUE)
library(methods)
knit(args[1], args[2])
purl(args[1])